#!/bin/sh

prog=rpathchk

perlrpaths()
{
	rm -rf "$1"
	mkdir "$1"
	cd "$1"
	xz -dc < "../$2" | tar -xvf - | xargs file | fgrep ELF | cut -d: -f1\
	| awk -v pkg="$1" '
	{
		needperl = foundperl = 0
		file = $1
		cmd = "readelf --dynamic " $1
		while((cmd | getline) > 0){
			if($2 == "(NEEDED)" && $5 ~ /libperl.so/){
				needperl = 1
			}else if($2 == "(RPATH)" && needperl && $5 ~ /perl/){
				print pkg, file, substr($5, 2, length($5)-2)
				foundperl = 1
			}
		}
		close(cmd)
		if(needperl && !foundperl){
			print pkg, file, "?"
		}
	}'
	cd ..
	rm -rf "$1"
}

cd
mkdir ".$prog"
cd ".$prog"

fetchpkgs $@ | while read repo pkg pkgfile
do
	perlrpaths "$pkg" "$pkgfile" || exit 1
done

ret=$?
if [ "$ret" -ne 0 ]
then
	echo "$prog: fetchpkgs returned code $ret" 1>&2
	exit 101
fi
