#!/usr/bin/env perl

use JSON::XS;
use Getopt::Std;

$PROG = 'webpkgs';

sub usage
{
	print STDERR "usage: $PROG [-m person] [-r repo] [search string]\n";
	exit 2;
}

sub err
{
	my $code = shift;
	print STDERR "$PROG: ", @_, "\n";
	exit $code;
}

getopts('m:r:') or usage;
$q = shift;
usage unless($q || $opt_m || $opt_r);

err(103, 'invalid char in query') if($q =~ /[^a-zA-Z -]/);

$url = "http://www.archlinux.org/packages/search/json/?limit=all&q=$q";
$url .= "&maintainer=$opt_m" if($opt_m);
$url .= "&repo=$opt_r" if($opt_r);
$json = `curl -q -s '$url'`;
err(101, sprintf("curl failed; code: %d output:\n%s", $? >> 8, $json)) if($?);

$srch = decode_json($json);
err(102, 'no results found') unless($srch->{'valid'});

@flds = qw/pkgname pkgver repo arch/;
for $p (@{$srch->{'results'}}){
	$p->{'pkgver'} .= q{-} . $p->{'pkgrel'};
	$p->{'pkgver'} .= '*' if($p->{'flag_date'});
	printf "%s\n", join "\t", (map { $p->{$_} } @flds),
		@{$p->{'maintainers'}};
}

exit 0;
